import {bedMobilitySPer} from "./bed mobility";
import {bedMobilitySupp} from "./bed mobility";
import {bladderVal} from "./bladder";
import {moodVal} from "./mood";
import {eatingSPer} from "./eating";
import {eatingSupp} from "./eating";
import {toiletingSupp} from "./toileting";
import {toiletingSPer} from "./toileting";
import {transfersSupp} from "./transfers";
import {transfersSPer} from "./transfers";
